FROM golang:latest

WORKDIR /app

COPY . .

# Download wait for it tool.
ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /wait-for-it
RUN chmod +x /wait-for-it

RUN go mod download
RUN go build -o main .